on: 
   [main]

jobs:
   test:
     #reuse development workflow
   
   build:
     steps:
       name: Test Application
        runs-on: ubuntu-latest
        steps:
           - name: Checkout repository
             uses: actions/checkout@v3
  
           - name: Setup node
             uses: actions/setup-node@v3
             with:
                node-version: '18.x'
  
           - name: Install dependencies
             run: npm ci
  
           - name: Run tests
             run: npm run test --if-present
      
       # build the project
       # upload build artifact -> use actions/upload-pages-artifact@v2
 
   deployment:
     # should run AFTER test and build (see `needs`) 
     steps:
        - name: Checkout repository
             uses: actions/checkout@v3
       # setup github pages -> use actions/configure-pages@v3
       # download the build artifacts -> use actions/download-artifact@v3
       # deploy to github pages -> use actions/deploy-pages@v2  
